#include "yeenboy/core/cpu/cpu.hpp"

int CPU::CBOpcode00() { return 0; }
int CPU::CBOpcode01() { return 0; }
int CPU::CBOpcode02() { return 0; }
int CPU::CBOpcode03() { return 0; }
int CPU::CBOpcode04() { return 0; }
int CPU::CBOpcode05() { return 0; }
int CPU::CBOpcode06() { return 0; }
int CPU::CBOpcode07() { return 0; }
int CPU::CBOpcode08() { return 0; }
int CPU::CBOpcode09() { return 0; }
int CPU::CBOpcode0A() { return 0; }
int CPU::CBOpcode0B() { return 0; }
int CPU::CBOpcode0C() { return 0; }
int CPU::CBOpcode0D() { return 0; }
int CPU::CBOpcode0E() { return 0; }
int CPU::CBOpcode0F() { return 0; }

int CPU::CBOpcode10() { return 0; }
int CPU::CBOpcode11() { return 0; }
int CPU::CBOpcode12() { return 0; }
int CPU::CBOpcode13() { return 0; }
int CPU::CBOpcode14() { return 0; }
int CPU::CBOpcode15() { return 0; }
int CPU::CBOpcode16() { return 0; }
int CPU::CBOpcode17() { return 0; }
int CPU::CBOpcode18() { return 0; }
int CPU::CBOpcode19() { return 0; }
int CPU::CBOpcode1A() { return 0; }
int CPU::CBOpcode1B() { return 0; }
int CPU::CBOpcode1C() { return 0; }
int CPU::CBOpcode1D() { return 0; }
int CPU::CBOpcode1E() { return 0; }
int CPU::CBOpcode1F() { return 0; }

int CPU::CBOpcode20() { return 0; }
int CPU::CBOpcode21() { return 0; }
int CPU::CBOpcode22() { return 0; }
int CPU::CBOpcode23() { return 0; }
int CPU::CBOpcode24() { return 0; }
int CPU::CBOpcode25() { return 0; }
int CPU::CBOpcode26() { return 0; }
int CPU::CBOpcode27() { return 0; }
int CPU::CBOpcode28() { return 0; }
int CPU::CBOpcode29() { return 0; }
int CPU::CBOpcode2A() { return 0; }
int CPU::CBOpcode2B() { return 0; }
int CPU::CBOpcode2C() { return 0; }
int CPU::CBOpcode2D() { return 0; }
int CPU::CBOpcode2E() { return 0; }
int CPU::CBOpcode2F() { return 0; }

int CPU::CBOpcode30() { return 0; }
int CPU::CBOpcode31() { return 0; }
int CPU::CBOpcode32() { return 0; }
int CPU::CBOpcode33() { return 0; }
int CPU::CBOpcode34() { return 0; }
int CPU::CBOpcode35() { return 0; }
int CPU::CBOpcode36() { return 0; }
int CPU::CBOpcode37() { return 0; }
int CPU::CBOpcode38() { return 0; }
int CPU::CBOpcode39() { return 0; }
int CPU::CBOpcode3A() { return 0; }
int CPU::CBOpcode3B() { return 0; }
int CPU::CBOpcode3C() { return 0; }
int CPU::CBOpcode3D() { return 0; }
int CPU::CBOpcode3E() { return 0; }
int CPU::CBOpcode3F() { return 0; }

int CPU::CBOpcode40() { return 0; }
int CPU::CBOpcode41() { return 0; }
int CPU::CBOpcode42() { return 0; }
int CPU::CBOpcode43() { return 0; }
int CPU::CBOpcode44() { return 0; }
int CPU::CBOpcode45() { return 0; }
int CPU::CBOpcode46() { return 0; }
int CPU::CBOpcode47() { return 0; }
int CPU::CBOpcode48() { return 0; }
int CPU::CBOpcode49() { return 0; }
int CPU::CBOpcode4A() { return 0; }
int CPU::CBOpcode4B() { return 0; }
int CPU::CBOpcode4C() { return 0; }
int CPU::CBOpcode4D() { return 0; }
int CPU::CBOpcode4E() { return 0; }
int CPU::CBOpcode4F() { return 0; }

int CPU::CBOpcode50() { return 0; }
int CPU::CBOpcode51() { return 0; }
int CPU::CBOpcode52() { return 0; }
int CPU::CBOpcode53() { return 0; }
int CPU::CBOpcode54() { return 0; }
int CPU::CBOpcode55() { return 0; }
int CPU::CBOpcode56() { return 0; }
int CPU::CBOpcode57() { return 0; }
int CPU::CBOpcode58() { return 0; }
int CPU::CBOpcode59() { return 0; }
int CPU::CBOpcode5A() { return 0; }
int CPU::CBOpcode5B() { return 0; }
int CPU::CBOpcode5C() { return 0; }
int CPU::CBOpcode5D() { return 0; }
int CPU::CBOpcode5E() { return 0; }
int CPU::CBOpcode5F() { return 0; }

int CPU::CBOpcode60() { return 0; }
int CPU::CBOpcode61() { return 0; }
int CPU::CBOpcode62() { return 0; }
int CPU::CBOpcode63() { return 0; }
int CPU::CBOpcode64() { return 0; }
int CPU::CBOpcode65() { return 0; }
int CPU::CBOpcode66() { return 0; }
int CPU::CBOpcode67() { return 0; }
int CPU::CBOpcode68() { return 0; }
int CPU::CBOpcode69() { return 0; }
int CPU::CBOpcode6A() { return 0; }
int CPU::CBOpcode6B() { return 0; }
int CPU::CBOpcode6C() { return 0; }
int CPU::CBOpcode6D() { return 0; }
int CPU::CBOpcode6E() { return 0; }
int CPU::CBOpcode6F() { return 0; }

int CPU::CBOpcode70() { return 0; }
int CPU::CBOpcode71() { return 0; }
int CPU::CBOpcode72() { return 0; }
int CPU::CBOpcode73() { return 0; }
int CPU::CBOpcode74() { return 0; }
int CPU::CBOpcode75() { return 0; }
int CPU::CBOpcode76() { return 0; }
int CPU::CBOpcode77() { return 0; }
int CPU::CBOpcode78() { return 0; }
int CPU::CBOpcode79() { return 0; }
int CPU::CBOpcode7A() { return 0; }
int CPU::CBOpcode7B() { return 0; }
int CPU::CBOpcode7C() { return 0; }
int CPU::CBOpcode7D() { return 0; }
int CPU::CBOpcode7E() { return 0; }
int CPU::CBOpcode7F() { return 0; }

int CPU::CBOpcode80() { return 0; }
int CPU::CBOpcode81() { return 0; }
int CPU::CBOpcode82() { return 0; }
int CPU::CBOpcode83() { return 0; }
int CPU::CBOpcode84() { return 0; }
int CPU::CBOpcode85() { return 0; }
int CPU::CBOpcode86() { return 0; }
int CPU::CBOpcode87() { return 0; }
int CPU::CBOpcode88() { return 0; }
int CPU::CBOpcode89() { return 0; }
int CPU::CBOpcode8A() { return 0; }
int CPU::CBOpcode8B() { return 0; }
int CPU::CBOpcode8C() { return 0; }
int CPU::CBOpcode8D() { return 0; }
int CPU::CBOpcode8E() { return 0; }
int CPU::CBOpcode8F() { return 0; }

int CPU::CBOpcode90() { return 0; }
int CPU::CBOpcode91() { return 0; }
int CPU::CBOpcode92() { return 0; }
int CPU::CBOpcode93() { return 0; }
int CPU::CBOpcode94() { return 0; }
int CPU::CBOpcode95() { return 0; }
int CPU::CBOpcode96() { return 0; }
int CPU::CBOpcode97() { return 0; }
int CPU::CBOpcode98() { return 0; }
int CPU::CBOpcode99() { return 0; }
int CPU::CBOpcode9A() { return 0; }
int CPU::CBOpcode9B() { return 0; }
int CPU::CBOpcode9C() { return 0; }
int CPU::CBOpcode9D() { return 0; }
int CPU::CBOpcode9E() { return 0; }
int CPU::CBOpcode9F() { return 0; }

int CPU::CBOpcodeA0() { return 0; }
int CPU::CBOpcodeA1() { return 0; }
int CPU::CBOpcodeA2() { return 0; }
int CPU::CBOpcodeA3() { return 0; }
int CPU::CBOpcodeA4() { return 0; }
int CPU::CBOpcodeA5() { return 0; }
int CPU::CBOpcodeA6() { return 0; }
int CPU::CBOpcodeA7() { return 0; }
int CPU::CBOpcodeA8() { return 0; }
int CPU::CBOpcodeA9() { return 0; }
int CPU::CBOpcodeAA() { return 0; }
int CPU::CBOpcodeAB() { return 0; }
int CPU::CBOpcodeAC() { return 0; }
int CPU::CBOpcodeAD() { return 0; }
int CPU::CBOpcodeAE() { return 0; }
int CPU::CBOpcodeAF() { return 0; }

int CPU::CBOpcodeB0() { return 0; }
int CPU::CBOpcodeB1() { return 0; }
int CPU::CBOpcodeB2() { return 0; }
int CPU::CBOpcodeB3() { return 0; }
int CPU::CBOpcodeB4() { return 0; }
int CPU::CBOpcodeB5() { return 0; }
int CPU::CBOpcodeB6() { return 0; }
int CPU::CBOpcodeB7() { return 0; }
int CPU::CBOpcodeB8() { return 0; }
int CPU::CBOpcodeB9() { return 0; }
int CPU::CBOpcodeBA() { return 0; }
int CPU::CBOpcodeBB() { return 0; }
int CPU::CBOpcodeBC() { return 0; }
int CPU::CBOpcodeBD() { return 0; }
int CPU::CBOpcodeBE() { return 0; }
int CPU::CBOpcodeBF() { return 0; }

int CPU::CBOpcodeC0() { return 0; }
int CPU::CBOpcodeC1() { return 0; }
int CPU::CBOpcodeC2() { return 0; }
int CPU::CBOpcodeC3() { return 0; }
int CPU::CBOpcodeC4() { return 0; }
int CPU::CBOpcodeC5() { return 0; }
int CPU::CBOpcodeC6() { return 0; }
int CPU::CBOpcodeC7() { return 0; }
int CPU::CBOpcodeC8() { return 0; }
int CPU::CBOpcodeC9() { return 0; }
int CPU::CBOpcodeCA() { return 0; }
int CPU::CBOpcodeCB() { return 0; }
int CPU::CBOpcodeCC() { return 0; }
int CPU::CBOpcodeCD() { return 0; }
int CPU::CBOpcodeCE() { return 0; }
int CPU::CBOpcodeCF() { return 0; }

int CPU::CBOpcodeD0() { return 0; }
int CPU::CBOpcodeD1() { return 0; }
int CPU::CBOpcodeD2() { return 0; }
int CPU::CBOpcodeD3() { return 0; }
int CPU::CBOpcodeD4() { return 0; }
int CPU::CBOpcodeD5() { return 0; }
int CPU::CBOpcodeD6() { return 0; }
int CPU::CBOpcodeD7() { return 0; }
int CPU::CBOpcodeD8() { return 0; }
int CPU::CBOpcodeD9() { return 0; }
int CPU::CBOpcodeDA() { return 0; }
int CPU::CBOpcodeDB() { return 0; }
int CPU::CBOpcodeDC() { return 0; }
int CPU::CBOpcodeDD() { return 0; }
int CPU::CBOpcodeDE() { return 0; }
int CPU::CBOpcodeDF() { return 0; }

int CPU::CBOpcodeE0() { return 0; }
int CPU::CBOpcodeE1() { return 0; }
int CPU::CBOpcodeE2() { return 0; }
int CPU::CBOpcodeE3() { return 0; }
int CPU::CBOpcodeE4() { return 0; }
int CPU::CBOpcodeE5() { return 0; }
int CPU::CBOpcodeE6() { return 0; }
int CPU::CBOpcodeE7() { return 0; }
int CPU::CBOpcodeE8() { return 0; }
int CPU::CBOpcodeE9() { return 0; }
int CPU::CBOpcodeEA() { return 0; }
int CPU::CBOpcodeEB() { return 0; }
int CPU::CBOpcodeEC() { return 0; }
int CPU::CBOpcodeED() { return 0; }
int CPU::CBOpcodeEE() { return 0; }
int CPU::CBOpcodeEF() { return 0; }

int CPU::CBOpcodeF0() { return 0; }
int CPU::CBOpcodeF1() { return 0; }
int CPU::CBOpcodeF2() { return 0; }
int CPU::CBOpcodeF3() { return 0; }
int CPU::CBOpcodeF4() { return 0; }
int CPU::CBOpcodeF5() { return 0; }
int CPU::CBOpcodeF6() { return 0; }
int CPU::CBOpcodeF7() { return 0; }
int CPU::CBOpcodeF8() { return 0; }
int CPU::CBOpcodeF9() { return 0; }
int CPU::CBOpcodeFA() { return 0; }
int CPU::CBOpcodeFB() { return 0; }
int CPU::CBOpcodeFC() { return 0; }
int CPU::CBOpcodeFD() { return 0; }
int CPU::CBOpcodeFE() { return 0; }
int CPU::CBOpcodeFF() { return 0; }