#include "yeenboy/core/cpu/cpu.hpp"

int CPU::Opcode00() { return OpcodeNOP(); }
int CPU::Opcode01() { return 0; }
int CPU::Opcode02() { return 0; }
int CPU::Opcode03() { return 0; }
int CPU::Opcode04() { return 0; }
int CPU::Opcode05() { return 0; }
int CPU::Opcode06() { return 0; }
int CPU::Opcode07() { return 0; }
int CPU::Opcode08() { return 0; }
int CPU::Opcode09() { return 0; }
int CPU::Opcode0A() { return 0; }
int CPU::Opcode0B() { return 0; }
int CPU::Opcode0C() { return 0; }
int CPU::Opcode0D() { return 0; }
int CPU::Opcode0E() { return 0; }
int CPU::Opcode0F() { return 0; }

int CPU::Opcode10() { return 0; }
int CPU::Opcode11() { return 0; }
int CPU::Opcode12() { return 0; }
int CPU::Opcode13() { return 0; }
int CPU::Opcode14() { return 0; }
int CPU::Opcode15() { return 0; }
int CPU::Opcode16() { return 0; }
int CPU::Opcode17() { return 0; }
int CPU::Opcode18() { return 0; }
int CPU::Opcode19() { return 0; }
int CPU::Opcode1A() { return 0; }
int CPU::Opcode1B() { return 0; }
int CPU::Opcode1C() { return 0; }
int CPU::Opcode1D() { return 0; }
int CPU::Opcode1E() { return 0; }
int CPU::Opcode1F() { return 0; }

int CPU::Opcode20() { return 0; }
int CPU::Opcode21() { return 0; }
int CPU::Opcode22() { return 0; }
int CPU::Opcode23() { return 0; }
int CPU::Opcode24() { return 0; }
int CPU::Opcode25() { return 0; }
int CPU::Opcode26() { return 0; }
int CPU::Opcode27() { return 0; }
int CPU::Opcode28() { return 0; }
int CPU::Opcode29() { return 0; }
int CPU::Opcode2A() { return 0; }
int CPU::Opcode2B() { return 0; }
int CPU::Opcode2C() { return 0; }
int CPU::Opcode2D() { return 0; }
int CPU::Opcode2E() { return 0; }
int CPU::Opcode2F() { return 0; }

int CPU::Opcode30() { return 0; }
int CPU::Opcode31() { return 0; }
int CPU::Opcode32() { return 0; }
int CPU::Opcode33() { return 0; }
int CPU::Opcode34() { return 0; }
int CPU::Opcode35() { return 0; }
int CPU::Opcode36() { return 0; }
int CPU::Opcode37() { return 0; }
int CPU::Opcode38() { return 0; }
int CPU::Opcode39() { return 0; }
int CPU::Opcode3A() { return 0; }
int CPU::Opcode3B() { return 0; }
int CPU::Opcode3C() { return 0; }
int CPU::Opcode3D() { return 0; }
int CPU::Opcode3E() { return 0; }
int CPU::Opcode3F() { return 0; }

int CPU::Opcode40() { return 0; }
int CPU::Opcode41() { return 0; }
int CPU::Opcode42() { return 0; }
int CPU::Opcode43() { return 0; }
int CPU::Opcode44() { return 0; }
int CPU::Opcode45() { return 0; }
int CPU::Opcode46() { return 0; }
int CPU::Opcode47() { return 0; }
int CPU::Opcode48() { return 0; }
int CPU::Opcode49() { return 0; }
int CPU::Opcode4A() { return 0; }
int CPU::Opcode4B() { return 0; }
int CPU::Opcode4C() { return 0; }
int CPU::Opcode4D() { return 0; }
int CPU::Opcode4E() { return 0; }
int CPU::Opcode4F() { return 0; }

int CPU::Opcode50() { return 0; }
int CPU::Opcode51() { return 0; }
int CPU::Opcode52() { return 0; }
int CPU::Opcode53() { return 0; }
int CPU::Opcode54() { return 0; }
int CPU::Opcode55() { return 0; }
int CPU::Opcode56() { return 0; }
int CPU::Opcode57() { return 0; }
int CPU::Opcode58() { return 0; }
int CPU::Opcode59() { return 0; }
int CPU::Opcode5A() { return 0; }
int CPU::Opcode5B() { return 0; }
int CPU::Opcode5C() { return 0; }
int CPU::Opcode5D() { return 0; }
int CPU::Opcode5E() { return 0; }
int CPU::Opcode5F() { return 0; }

int CPU::Opcode60() { return 0; }
int CPU::Opcode61() { return 0; }
int CPU::Opcode62() { return 0; }
int CPU::Opcode63() { return 0; }
int CPU::Opcode64() { return 0; }
int CPU::Opcode65() { return 0; }
int CPU::Opcode66() { return 0; }
int CPU::Opcode67() { return 0; }
int CPU::Opcode68() { return 0; }
int CPU::Opcode69() { return 0; }
int CPU::Opcode6A() { return 0; }
int CPU::Opcode6B() { return 0; }
int CPU::Opcode6C() { return 0; }
int CPU::Opcode6D() { return 0; }
int CPU::Opcode6E() { return 0; }
int CPU::Opcode6F() { return 0; }

int CPU::Opcode70() { return 0; }
int CPU::Opcode71() { return 0; }
int CPU::Opcode72() { return 0; }
int CPU::Opcode73() { return 0; }
int CPU::Opcode74() { return 0; }
int CPU::Opcode75() { return 0; }
int CPU::Opcode76() { return 0; }
int CPU::Opcode77() { return 0; }
int CPU::Opcode78() { return 0; }
int CPU::Opcode79() { return 0; }
int CPU::Opcode7A() { return 0; }
int CPU::Opcode7B() { return 0; }
int CPU::Opcode7C() { return 0; }
int CPU::Opcode7D() { return 0; }
int CPU::Opcode7E() { return 0; }
int CPU::Opcode7F() { return 0; }

int CPU::Opcode80() { return 0; }
int CPU::Opcode81() { return 0; }
int CPU::Opcode82() { return 0; }
int CPU::Opcode83() { return 0; }
int CPU::Opcode84() { return 0; }
int CPU::Opcode85() { return 0; }
int CPU::Opcode86() { return 0; }
int CPU::Opcode87() { return 0; }
int CPU::Opcode88() { return 0; }
int CPU::Opcode89() { return 0; }
int CPU::Opcode8A() { return 0; }
int CPU::Opcode8B() { return 0; }
int CPU::Opcode8C() { return 0; }
int CPU::Opcode8D() { return 0; }
int CPU::Opcode8E() { return 0; }
int CPU::Opcode8F() { return 0; }

int CPU::Opcode90() { return 0; }
int CPU::Opcode91() { return 0; }
int CPU::Opcode92() { return 0; }
int CPU::Opcode93() { return 0; }
int CPU::Opcode94() { return 0; }
int CPU::Opcode95() { return 0; }
int CPU::Opcode96() { return 0; }
int CPU::Opcode97() { return 0; }
int CPU::Opcode98() { return 0; }
int CPU::Opcode99() { return 0; }
int CPU::Opcode9A() { return 0; }
int CPU::Opcode9B() { return 0; }
int CPU::Opcode9C() { return 0; }
int CPU::Opcode9D() { return 0; }
int CPU::Opcode9E() { return 0; }
int CPU::Opcode9F() { return 0; }

int CPU::OpcodeA0() { return 0; }
int CPU::OpcodeA1() { return 0; }
int CPU::OpcodeA2() { return 0; }
int CPU::OpcodeA3() { return 0; }
int CPU::OpcodeA4() { return 0; }
int CPU::OpcodeA5() { return 0; }
int CPU::OpcodeA6() { return 0; }
int CPU::OpcodeA7() { return 0; }
int CPU::OpcodeA8() { return 0; }
int CPU::OpcodeA9() { return 0; }
int CPU::OpcodeAA() { return 0; }
int CPU::OpcodeAB() { return 0; }
int CPU::OpcodeAC() { return 0; }
int CPU::OpcodeAD() { return 0; }
int CPU::OpcodeAE() { return 0; }
int CPU::OpcodeAF() { return 0; }

int CPU::OpcodeB0() { return 0; }
int CPU::OpcodeB1() { return 0; }
int CPU::OpcodeB2() { return 0; }
int CPU::OpcodeB3() { return 0; }
int CPU::OpcodeB4() { return 0; }
int CPU::OpcodeB5() { return 0; }
int CPU::OpcodeB6() { return 0; }
int CPU::OpcodeB7() { return 0; }
int CPU::OpcodeB8() { return 0; }
int CPU::OpcodeB9() { return 0; }
int CPU::OpcodeBA() { return 0; }
int CPU::OpcodeBB() { return 0; }
int CPU::OpcodeBC() { return 0; }
int CPU::OpcodeBD() { return 0; }
int CPU::OpcodeBE() { return 0; }
int CPU::OpcodeBF() { return 0; }

int CPU::OpcodeC0() { return 0; }
int CPU::OpcodeC1() { return 0; }
int CPU::OpcodeC2() { return 0; }
int CPU::OpcodeC3() { return 0; }
int CPU::OpcodeC4() { return 0; }
int CPU::OpcodeC5() { return 0; }
int CPU::OpcodeC6() { return 0; }
int CPU::OpcodeC7() { return 0; }
int CPU::OpcodeC8() { return 0; }
int CPU::OpcodeC9() { return 0; }
int CPU::OpcodeCA() { return 0; }
int CPU::OpcodeCB() { return 0; }
int CPU::OpcodeCC() { return 0; }
int CPU::OpcodeCD() { return 0; }
int CPU::OpcodeCE() { return 0; }
int CPU::OpcodeCF() { return 0; }

int CPU::OpcodeD0() { return 0; }
int CPU::OpcodeD1() { return 0; }
int CPU::OpcodeD2() { return 0; }
int CPU::OpcodeD3() { return 0; }
int CPU::OpcodeD4() { return 0; }
int CPU::OpcodeD5() { return 0; }
int CPU::OpcodeD6() { return 0; }
int CPU::OpcodeD7() { return 0; }
int CPU::OpcodeD8() { return 0; }
int CPU::OpcodeD9() { return 0; }
int CPU::OpcodeDA() { return 0; }
int CPU::OpcodeDB() { return 0; }
int CPU::OpcodeDC() { return 0; }
int CPU::OpcodeDD() { return 0; }
int CPU::OpcodeDE() { return 0; }
int CPU::OpcodeDF() { return 0; }

int CPU::OpcodeE0() { return 0; }
int CPU::OpcodeE1() { return 0; }
int CPU::OpcodeE2() { return 0; }
int CPU::OpcodeE3() { return 0; }
int CPU::OpcodeE4() { return 0; }
int CPU::OpcodeE5() { return 0; }
int CPU::OpcodeE6() { return 0; }
int CPU::OpcodeE7() { return 0; }
int CPU::OpcodeE8() { return 0; }
int CPU::OpcodeE9() { return 0; }
int CPU::OpcodeEA() { return 0; }
int CPU::OpcodeEB() { return 0; }
int CPU::OpcodeEC() { return 0; }
int CPU::OpcodeED() { return 0; }
int CPU::OpcodeEE() { return 0; }
int CPU::OpcodeEF() { return 0; }

int CPU::OpcodeF0() { return 0; }
int CPU::OpcodeF1() { return 0; }
int CPU::OpcodeF2() { return 0; }
int CPU::OpcodeF3() { return 0; }
int CPU::OpcodeF4() { return 0; }
int CPU::OpcodeF5() { return 0; }
int CPU::OpcodeF6() { return 0; }
int CPU::OpcodeF7() { return 0; }
int CPU::OpcodeF8() { return 0; }
int CPU::OpcodeF9() { return 0; }
int CPU::OpcodeFA() { return 0; }
int CPU::OpcodeFB() { return 0; }
int CPU::OpcodeFC() { return 0; }
int CPU::OpcodeFD() { return 0; }
int CPU::OpcodeFE() { return 0; }
int CPU::OpcodeFF() { return 0; }